components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
=> Merge Release 5.1.1 to master

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
Reverts wso2-extensions/identity-outbound-auth-oidc#19
=> Revert "IDENTITY-6529: Improving unit tests in identity-outbound-auth-oidc component"

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
> Writing unit tests for the oauth-oidc component
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> IDENTITY-6529:Improving unit tests oidc component

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/internal/OpenIDConnectAuthenticatorDataHolder.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/internal/OpenIDConnectAuthenticatorServiceComponent.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, pom.xml
- IDENTITY-6349: Fix subject value not picked among claims in id_token
- Immediately
- N/A
=> IDENTITY-6349: Fix subject value not picked among claims in id_token

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Originals parameters would be referenced in Identity Provider's "Additional Query Parameters" config field.
For example :
param1=fixedParam&param2=${paramNameInOriginalRequest}
https://stackoverflow.com/questions/44542667/wso2-apim-is-forward-scopes-to-oidc-identity-provider
- Enable forwarding original parameters to Identity Provider's authorization endpoint
environments.]
-
=> Enable forwarding original parameters to Identity Provider's authorization endpoint

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, pom.xml
=> Fixing https://github.com/wso2/product-is/issues/2678

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
=> Fixing possible NPE

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, pom.xml
Resolves wso2/product-is#3138
ASAP
=> Support client authentication with basic authentication scheme.

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
$subject
Fixes https://github.com/wso2/product-is/issues/4552
=> Fix possible NPE if user id claim URI is not configured and 'User ID found among claims' option is selected

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
OIDC federated authenticator cannot process claims in id_token
Immediately
None
=> Fix OIDC federated authenticator cannot process claims in id_token

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, pom.xml
This PR contains changes to manipulate the multi-valued claims correctly. It resolves the issue - https://github.com/wso2/product-is/issues/5154.
=> Fix provisioning of claims which is in the format of Object []

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, pom.xml
Resolves https://github.com/wso2/product-is/issues/5154
=> Fixing error occured when provisioning user with the claims returned from userinfo endpoint

.travis.yml, pom.xml
This PR needs to be merged only after wso2/orbit#373 is merged and the nimbusds orbit bundle is released.
Part of wso2/product-is#5786
=> Upgrade nimbusds-jose-jwt library

.travis.yml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
Fixes https://github.com/wso2/product-is/issues/5971
Travis build failure fix from https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/44/commits/0fdc0fc23518a3809638ccb363ea83b7b587ffb6
=> Enable Origin header in Token request

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, pom.xml
=> Update to pax logging

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- Resolves wso2/product-is#5998
=> Support base64 encode with padding

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
$subject as a part of https://github.com/wso2/product-is/issues/5958
=> Handle RP initiated OIDC federated logout

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/model/OIDCStateInfo.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/model/StateInfoOIDC.java
$subject as a part of wso2/product-is#5958
=> Support for id_token_hint hint param in OIDC federated Logout

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, pom.xml
=> Add configuration properties required for REST APIs

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Resolving conflicts in https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/34
=> Avoid NullPointer and ClassCastExceptions

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Resolves https://github.com/wso2/product-is/issues/7689
=> Avoid possible ArrayIndexOutOfBound exception

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/model/OIDCStateInfo.java, pom.xml
Resolves https://github.com/wso2/product-is/issues/5958
Backport this https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/62, https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/63/
=> Support Federate logout request to OIDC IDPs

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
=> Upgrade Carbon Kernel version

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Fixes https://github.com/wso2/product-is/issues/7983
=> Fix isConfidential should be true for Client Secret field

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
Resolves : https://github.com/wso2/product-is/issues/8149
environments.]
-
=> Add the required additional query params in the OIDC response

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, pom.xml
Addresses https://github.com/wso2/product-is/issues/8156
=> Tenant qualify OIDC outbound authenticator

.gitignore, components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, pom.xml
Related https://github.com/wso2/product-is/issues/8042
=> Upgrade commons codec to v1.14.0-wso2v1

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/util/OIDCErrorConstants.java, pom.xml
PR covers
added Error codes for OIDC authenticator using the code "OID-XXXXX"
Resolves wso2/product-is#8667
=> add error codes for OIDC

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Fix for https://github.com/wso2/product-is/issues/10038. Additional query parameter is not URL encoded. We have to URL encode before concatenating it with login page URL.
=> Fix internal server error when using Google as a federated authenticator

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
$subject.
Fix in https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/83 for the version 5.5.2.
=> Validate for code parameter in the request for canHandle method.

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
=> Update project version in the 5.5.x branch.

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
$subject
Resolves https://github.com/wso2/product-is/issues/10533.
Resolves https://github.com/wso2/product-is/issues/10057.
=> Override process method to validate for the code parameter in the request.

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- Add SId claim coming from the federated identity provider to authentication context
Related to https://github.com/wso2/product-is/issues/10714
=> Add sid claim to context

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
=> [IS 5.10.0]Fix OIDC error flow by validating the request params

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
> Fixes https://github.com/wso2/product-is/issues/10697
Fixed the OIDC error flow
=> Fix OIDC error flow by validating the request params

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
This PR adds support to filter non-user attributes coming in the ID token from FIDP side. Following attributes will be removed after the filtering.
```
"at_hash", "iss", "iat", "exp", "aud", "azp"
```
=> Add support to filter non user attributes in the ID token coming from the FIDP

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
Reverts wso2-extensions/identity-outbound-auth-oidc#104
=> Revert "Change JIT provisioned Managed profile name"

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
Update to SNAPSHOT version
-
environments.]
-
=> Update version to SNAPSHOT

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
Porting the fixes https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/87 and https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/90 to 5.6.x version to fix https://github.com/wso2/api-manager/issues/452 in APIM manager 4.1.0.
=> Porting Fixes to 5.6.x branch

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
=> Bump Kernel Version

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Reverts wso2-extensions/identity-outbound-auth-oidc#119
=> Revert "Integrating Google One Tap"

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
Bump version to 5.10.0-SNAPSHOT
=> Bump version to 5.10.0-SNAPSHOT

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Related to https://github.com/wso2/product-is/issues/14407
Integrating Google One Tap - BE changes.
Generalizing OpenIDConnectAuthenticator to accommodate Google One Tap flow.
Dependencies
identity-framework
identity-apps
=> Implementing Google One Tap

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessor.java
=> Modify the logout processor to cater custom requirements

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
- Refactoring the pom versions to match with the branch.
=> [5.9.x] Refactoring pom Versions

.github/workflows/pr-builder.yml, README.md, components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessor.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessorTest.java, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
Get latest changes from master and update pom to 6.0.0 major version for IPK.
=> Update pom to Major Development Version

pom.xml
=> Update Carbon Kernel version

pom.xml
=> Bump Carbon Kernel version

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, pom.xml
=> Remove carbon.ui dependency

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
=> Update carbon-identity-framework version range

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/factory/LogoutResponseFactory.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessor.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/factory/LogoutRequestFactoryTest.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessorTest.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/resources/conf/application-authentication.xml
=> Remove extra line

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
=> Fix for google one tap failure

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
This PR fixes a bug where the logout request not passed down to the 3rd IS instance when at least 3 IS are chained as federated IDPs. This causes the SLO flow to not work as expected.
=> Handle federated logout when multiple IS instances are chained as federated IDPs

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
This PR improves the method descriptions of getScope() methods in OpenIDConnectAuthenticator. Addresses comment https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/124#discussion_r1206206391
=> Add descriptive method descriptions

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
$subject.
This PR removes the URL encoding happening in [1] because, the query parameters will be encoded at [2] when the request passes through `initiateAuthenticationRequest`. 
https://github.com/Shaaali/identity-outbound-auth-oidc/blob/1ae27ee2c10a3ba9503b05bf1dbf2055df8251b8/components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java#L398
https://github.com/Shaaali/identity-outbound-auth-oidc/blob/1ae27ee2c10a3ba9503b05bf1dbf2055df8251b8/components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java#L411
-
[Please describe any preconditions that need to be addressed before …
=> Remove Double Encoding of URL Query Parameters. 

.github/workflows/pr-builder.yml
=> Opt out of stricter validations in Java patch update

.github/workflows/pr-builder.yml
=> Change java version in the PR builder

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, pom.xml
Modify the OIDC Authenticator to support for the API Based Authentication.
=> Modify the OIDC Authenticator to support for the API Based Authentication

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
Modify the logics related to AdditionalData
=> Modify the logics related to AdditionalData

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
$Subject
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/154
- https://github.com/wso2/product-is/issues/15684
=> Improve "canHandle" Method to Support Native SDK based Federation

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, pom.xml
$Subject
- https://github.com/wso2/carbon-identity-framework/pull/5029
=> Apply Framework Authentication Service Changes

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, pom.xml
Modify the redirect url for API Based Auth
=> Modify the redirect url for API Based Auth

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Set message to AuthenticatorData
=> Set message to AuthenticatorData

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, pom.xml
Related to https://github.com/wso2/product-is/issues/15684
=> Change state value for api based auth

pom.xml
- Upgrade the json version to 3.0.0.wso2v4
https://github.com/wso2/product-is/issues/17932
environments.]
-
=> Upgrade json version to 3.0.0.wso2v4

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Resolves https://github.com/wso2/product-is/issues/18273
Related to https://github.com/wso2/product-is/issues/15684
=> Send scope as an additional param for native api based auth

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
=> Changing pom versions for development

components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml, pom.xml
=> Changing snapshot version for next release version

pom.xml
$subject
Related issue: https://github.com/wso2/api-manager/issues/2526
=> [5.11.x] Upgrade nimbus to 9.37.3

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- $Subject
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/154
=> Update License Header in `OIDCAuthenticatorConstants`

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Fixes https://github.com/wso2/api-manager/issues/3015
=> Fix Role Mapping Without Using the User Info Endpoint in Federated Authentication

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
$subject to fix https://github.com/wso2/product-is/issues/22668
=> Update the PKCE constant to reflect the value in the authenticator configs

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
=> Change IS_PKCE_ENABLED constant

.github/workflows/pr-builder.yml, components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCSocialSignupExecutor.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/internal/OpenIDConnectAuthenticatorServiceComponent.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/util/OIDCExecutorUtil.java, components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java, pom.xml
Related to https://github.com/wso2/product-is/issues/23356
The changes suggested here have duplicates with the OpenIDConnectAuthenticator. The authenticators and the executors will be refactored to reduce the code duplication via a separate effort. This is tracked in https://github.com/wso2/product-is/issues/23431
-
environments.]
-
=> Add oidc registration executor

pom.xml
Get the change introduced with https://github.com/wso2/carbon-identity-framework/pull/6610
environments.]
-
=> Bump identity-framework version

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCSocialSignupExecutor.java
=> Modify the registration portal endpoint

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Issue:
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/3429
Note $subject
Related PR:
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/204
=> Update URL decoding code to be compatible with java8

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Related to https://github.com/wso2/product-is/issues/24158
=> Add logout endpoint url as oidc authenticator property

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectExecutor.java
=> Use portal URL

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectExecutor.java
Provide capability to append additional query params to the authorize call
https://github.com/wso2-enterprise/asgardeo-product/issues/31433
=> Support for additional query params

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessor.java
The `validateEventClaim` method accepts a `net.minidev.json.JSONObject` as its parameter. Previously, the call to `claimsSet.getClaim(OIDCAuthenticatorConstants.Claim.EVENTS)` returned an object of the same type, allowing inline casting without issue.
However, following a version upgrade of the `nimbus-jose-jwt` library, the claim is now returned as a GSON `LinkedTreeMap`, resulting in a `ClassCastException`.
This pull request introduces a safe handling mechanism for both legacy and updated return types, ensuring compatibility while preserving the original behavior.
https://github.com/wso2/api-manager/issues/4019
=> Add proper type casting for validating event claim

components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectExecutor.java
1. Honor `isJITProvisionEnhancedFeatureEnabled` when setting the federatedUserId as the username.
2. If the username is already present in the flowUser, prevent overriding the value
https://github.com/wso2/product-is/issues/24836
=> Add JIT provisioning enhancement enabled
