- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
- pom.xml
- We need to be able to run this connector on IS 5.3.0 as well. IS 5.3.0 supports both Java7 and Java8. Therefore fixing the target version to java 1.7 until we come to clear conclusion on how we are going to move to Java8.
> Change target version to java7 to ensure backward compatibility with IS 5.3.0

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
While experimenting with federated authentication using a Salesforce instance, we received a token like this:
`{at_hash=xxx, sub=https://test.salesforce.com/id/xxx/xxx, zoneinfo=GMT, email_verified=true, address={}, profile=https://xxxx, iss=https://xxxx, preferred_username=first.last@email.de, given_name=First, locale=de_DE_EURO, picture=https://xxx/img/userprofile/default_profile_200_v2.png,  aud=xxx, updated_at=2018-10-09T07:01:23Z, nickname=xxx, name=First Last, phone_number=null, exp=1539068692, iat=1539068572, family_name=Last, email=first.last@email.de}`
The claims mapping results in an authentication error caused by the following expection:
```
ERROR {org.wso2.carbon.identity.application.authentication.framework.handler.request.impl.DefaultRequestCoordinator} -  Exception in …
```
> fixed NullPointerException that occurred when claims contain null value

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
- pom.xml
Partially solves https://github.com/wso2/product-is/issues/5437
Related to https://github.com/wso2/carbon-identity-framework/pull/2246
The PR implements code changes to support the usage of default claim dialect for OIDC authenticators. The code checks for UI property and if not available checks for a global config. If both configurations are not available it will call the earlier used getClaimDialectURI() method to keep the previous behaviour intact.  
It is possible to add the following configuration to the application-authentication.xml in `<AuthenticatorConfigs>` under  `<AuthenticatorConfig name="OpenIDConnectAuthenticator" enabled="true">` to set a global configuration to use the default claim dialect instead of the OIDC claim dialect for authenticators using the OIDC claim dialect. …
> Add ability to use default claim dialect for OIDC authenticators

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
- pom.xml
Reverts wso2-extensions/identity-outbound-auth-oidc#42
PR is reverted as the fix has been changed.
> Revert "Add ability to use default claim dialect for OIDC authenticators"

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
With the changes done in wso2/carbon-identity-framework#xxxx
the logout url added by the user is extracted and used at initiating the logout request.
Fixes: wso2/product-is#5958
> Handle RP initiated OIDC federated logout

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
In the OIDC Authenticator, the canHandle() returns true whenever the state parameter for the request satisfy the loginType condition.
This fails in a scenario as described https://github.com/wso2/product-is/issues/10057, where there are more than one redirections before the user is prompted for authentication and an authorization code is returned. In such scenarios as per the current behaviour, the OIDC Authenticator would call the processAuthenticationResponse, even if no code parameter is returned in the request.
Resolves https://github.com/wso2/product-is/issues/10057.
> Validate for code parameter in the request for canHandle method.

- components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml
- features/org.wso2.carbon.identity.application.authenticator.oidc.server.feature/pom.xml
- pom.xml
Bump the project version to 5.6.x. The reason being the IS-5.10 version is compatible with the connector version 5.5.2. 
From 5.5.3 and onwards, the connector is compatible only with IS-5.11. For clarity, we can update the project version to 5.6.x and denote that v5.6.0 and onwards would be compatible with IS-5.11.
> Update project-version to 5.6.x

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Related https://github.com/wso2-enterprise/asgardeo-product/issues/6394
Add a new constant  `AUTHENTICATOR_FRIENDLY_NAME`.
> Add a new constant `AUTHENTICATOR_FRIENDLY_NAME`

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
- pom.xml
For an OIDC external IdP, OIDC scope configuration controls which attributes are requested from the configured external IdP. In the on-prem IS, the default scope is set to openid. For setting additional scopes,  the Additional Query Parameters input field has to be used, where we can define the scope values as a space separated string. 
It is a requirement of the majority of application developers to get user attributes such as first name, email, etc. from an external IdP after authentication. Therefore configuring the scope in the IdP configuration becomes an important step.
This fix makes the scope a first class attribute by adding a separate field in the UI to add scope values.
Related issue: https://github.com/wso2/product-is/issues/14845
> Set OIDC scopes as a primary field in OpenIdConnectAuthenticator Configuration

- components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
- pom.xml
* Add diagnostic logs to the outbound OIDC authenticator
Diagnostic logs will be covered the green-colored actions/validations of the authentication process. 
1. Authentication Request Validation
Within each authenticator, the `initiateAuthenticationRequest` method houses the logic for this step. This triggers two diagnostic logs. The first log indicates the initialization of the authentication request, and the second log shows the authentication request has been successfully sent – whether it's a Success or marked Invalid.
2. Validate Authentication Response
The `processAuthenticationResponse` method handles authentication responses sent by the federated IDP. Once users are sent to the federated IDP page and complete the login, the authenticator receives an authentication response sent …
> Add diagnostic logs to the authenticator

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/util/OIDCErrorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/util/OIDCTokenValidationUtil.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/util/OIDCTokenValidationUtilTest.java
- pom.xml
- Exceptions thrown by `validateJWTToken()` method are differentiated whether they are client or server exceptions and handheld accordingly.
- Avoid possible null pointer exception by swapping the values used in equal check inside `isTrustedTokenIssuer()` method.
- Add more unit tests into `OpenIDConnectAuthenticatorTest` and `OIDCTokenValidationUtilTest` classes in order to verify API based authentication functionality of the OIDC authenticator.
- Bump framework version.
> Improve Exception Handling and Add Unit Tests for API based Authentication

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/util/OIDCErrorConstants.java
- pom.xml
Error handling in OIDC authenticator
> Error handling in OIDC authenticator

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- Add a protected method named `resolveCallBackURLForAPIBasedAuthFlow ` to resolve the callback in the API_BASED authentication flow.
- Changing the callback URL to the client application's callback URL in  `initiateAuthenticationRequest` method and `getAccessTokenRequest` could affect the OIDC authenticators used for internal purposes.
- resolveCallBackURLForAPIBasedAuthFlow method gives the capability to override the behavior in other authenticators if required.
Part of the first issue of https://github.com/wso2/product-is/issues/19668
> Add callback resolver method

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- Extract login page creation in `initiateAuthenticationRequest()` method into protected method.
> Refactor Login Page Creation in `initiateAuthenticationRequest` Method

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
- Add unit tests for `getApplicationDetails()` and `extractScopesFromURL()` methods.
- https://github.com/wso2/product-is/issues/20159
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/177
> Add Unit Tests

- components/org.wso2.carbon.identity.application.authenticator.oidc/pom.xml
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
This PR enables PKCE in OIDC federated login flow. In IDP configurations, a new checkbox has been introduced under Federated configurations to enable/disable PKCE in PR[1] and upon enabling the checkbox respective `code_verifier` and `code_challenge` parameters are added to the authentication and token requests.
Related to https://github.com/wso2/api-manager/issues/1613
[1] https://github.com/wso2/carbon-identity-framework/pull/4500
> Enable PKCE in OIDC federated login flow

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessor.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessorTest.java
- pom.xml
> Improve federated idp initiated logout for multiple IDP sessions

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
When adding the properties such as redirect_url, scope, state and nonce into the authentication context, use the specific authenticator name as the prefix to uniquely identify the specific keys according to each authenticator.
Related issue:
- https://github.com/wso2/product-is/issues/20584
> Change authenticator property keys to be specific for different authenticators

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
When configuring the authentication steps for a service provider, if the first step has multiple authentication choices between with an OIDC federated IdP as one of them, when the user picks the federated IdP, they are redirected to the federated IdP's login page to proceed. 
When this redirection happens, the URL query parameters originally included in the request are encoded and included in the request as a parameter called multiOptionURI. 
When parsing the request's query parameters to interpret the additional query parameters, the encoded value of multiOptionURI is not considered.
With this PR, if the additional query parameter isn't present in the request parameters, it will check if the multiOptionURI parameter is available and check if the additional query parameter is present here …
> Add multiOptionURI parsing for additional query parameters

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
The getParameterFromURIString method is responsible for retrieving dynamic query parameters of the IDP from the multiOptionURI when redirecting from the multi-option page. However, since the multiOptionURI parameter is encoded, it must be decoded before extracting the parameters. Failing to do so can alter the original values of the dynamic parameters
- https://github.com/wso2/product-is/issues/22859
> Decode dynamic query parameters when fetching from the multiOptionURI

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessor.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/logout/idpinit/processor/FederatedIdpInitLogoutProcessorTest.java
Currently in federated IDP initiated backchannel logout using SID claim, the session data store data and federated user session mapping data is removed but auth user session data is not removed. With this PR, auth user session data are also removed when executing the backchannel logout.
Related Issue - https://github.com/wso2/product-is/issues/23024
> Remove auth session data in backchannel logout

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OIDCAuthenticatorConstants.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
Issue:
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/3429
When configuring the authentication steps for a service provider, if the first step has multiple authentication choices between with an OIDC federated IdP as one of them, when the user picks the federated IdP, they are redirected to the federated IdP's login page to proceed. 
When this redirection happens, the URL query parameters originally included in the request are encoded and included in the request as a parameter called multiOptionURI. 
When parsing the request's query parameters to interpret the additional query parameters, the encoded value of multiOptionURI is not considered.
With this PR, if the additional query parameter isn't present in the request parameters, it will check if the multiOptionURI …
> Add multiOptionURI parsing for additional query params

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticator.java
- components/org.wso2.carbon.identity.application.authenticator.oidc/src/test/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectAuthenticatorTest.java
Issue:
- https://github.com/wso2-enterprise/wso2-iam-internal/issues/3505
This resolves the issue where, when multiple custom parameters are passed, an empty value is replaced by neighboring values instead of being passed as an empty value.
Public PR:
- https://github.com/wso2-extensions/identity-outbound-auth-oidc/pull/206
> Unexpected behavior when passing empty values to authenticatorParams in Adaptive Auth

- components/org.wso2.carbon.identity.application.authenticator.oidc/src/main/java/org/wso2/carbon/identity/application/authenticator/oidc/OpenIDConnectExecutor.java
- pom.xml
This pull request refactors and enhances the `OpenIDConnectExecutor` class to improve user identification handling and updates the dependency version in the `pom.xml` file. The key changes include the removal of redundant methods, the introduction of new methods to manage federated user identifiers, and the update of the `carbon.identity.framework.version` dependency.
https://github.com/wso2/product-is/issues/24788
* Removed the `getSubjectFromUserIDClaimURI` method and replaced it with a more robust mechanism for resolving federated usernames, including the introduction of the `getFederatedUsername` and `getFederatedUserId` methods. These methods ensure proper handling of federated user identifiers and fallback mechanisms. [[1]](diffhunk://#diff-56dbb354c4d1a911bcce8284246cca7594cfc8c4592 …
> Improve username resolving logic and association handling
